### ISSUE TITLE
appstream-util doesn't compare versions correctly

### ISSUE THREAD

**Issue by scx** [hughsie/appstream-glib#270]
It seems that appstream-util doesn't compare versions correctly, which leads to incorrect validation of AppData files.

```
$ appstream-util --version
Version:	0.7.13
```

```
$ appstream-util vercmp "Build 9half" "Build 10"
Build 9half > Build 10
$ appstream-util vercmp "Build 9.5" "Build 10"
Build 9.5 > Build 10
$ appstream-util vercmp "Build 9+" "Build 10"
Build 9+ > Build 10
$ appstream-util vercmp "Build 9a" "Build 10"
Build 9a > Build 10
$ appstream-util vercmp "Build 9" "Build 10"
Build 9 > Build 10
```

```
$ appstream-util vercmp "9half" "10"
9half > 10
$ appstream-util vercmp "9.5" "10"
9.5 > 10
$ appstream-util vercmp "9+" "10"
9+ > 10
$ appstream-util vercmp "9a" "10"
9a > 10
$ appstream-util vercmp "9" "10"
9 < 10
```

As you can see, only the last result is correct.
The problem occurs in both Freedesktop 1.6 and 18.08.

Please compare this with the rpmdev-vercmp on RHEL 7:

```
$ rpm -q --qf "%{VERSION}\n" rpmdevtools
8.3
```

```
$ rpmdev-vercmp "Build 9half" "Build 10"
Build 9half < Build 10
$ rpmdev-vercmp "Build 9.5" "Build 10"
Build 9.5 < Build 10
$ rpmdev-vercmp "Build 9+" "Build 10"
Build 9+ < Build 10
$ rpmdev-vercmp "Build 9a" "Build 10"
Build 9a < Build 10
$ rpmdev-vercmp "Build 9" "Build 10"
Build 9 < Build 10
```

```
$ rpmdev-vercmp "9half" "10"
9half < 10
$ rpmdev-vercmp "9.5" "10"
9.5 < 10
$ rpmdev-vercmp "9+" "10"
9+ < 10
$ rpmdev-vercmp "9a" "10"
9a < 10
$ rpmdev-vercmp "9" "10"
9 < 10
```

See also: https://github.com/widelands/widelands/blob/600993f5051752cf7af2a9d572da0ffbb01d8089/debian/widelands.appdata.xml#L265-L284

**Comment by hughsie** [comment]
I did my best with the rpmdevcmp implementation. Can you try with appstream-glib git master and tell me if that's any better, I know we added a few fixes in there recently for version comparison.

**Comment by smcv** [comment]
Is there a specification for how Appstream compares versions? dpkg has a formal specification [in Debian Policy](https://www.debian.org/doc/debian-policy/ch-controlfields.html#version); I don't know whether RPM has an equivalent. If Appstream doesn't have a specification (which might as well be borrowed from some packaging system that has one) then I suspect it'll never quite match expectations; conversely, if it has a specification, then any expectation that doesn't match the spec can be declared to be wrong.

The various models of how to compare a version are probably all the same in simple cases, but not in corner cases like dpkg's rule that "The lexical comparison is a comparison of ASCII values modified so that all the letters sort earlier than all the non-letters and so that a tilde sorts before anything, even the end of a part" (so in particular 1.0~rc1 < 1.0 < 1.0ubuntu1 < 1.0+git20181108 < 1.0.1).

Obviously as a Debian developer I'm biased, but I think dpkg's specification is as good as any other here, and it has the advantage of having already been written down as a non-implementation-dependent specification. If RPM has a similar specification then I'm sure that would also be fine.

**Comment by scx** [comment]
This is not the first time this has happened. [Blender](https://github.com/hughsie/appstream-glib/issues/231) had a similar problem a couple months ago.
In my opinion, version comparison should be excluded from validation of AppData files. This only causes unnecessary problems. What's more, the implementation changes from version to version, which cause different results on different systems. How developers should deal with this? Moreover, if vendors have used a specified version scheme for many years, you can't just say now that they did it wrong.
Please keep in mind, that AppData validation is required by Flatpak. If it fails, build will fail as well.

I prepared a simple test: [org.freedesktop.appstream-test.yaml](https://paste.ubuntu.com/p/fCHPsd7Mxb/)
```
app-id: org.freedesktop.appstream-test
runtime: org.freedesktop.Platform
runtime-version: '18.08'
sdk: org.freedesktop.Sdk
command: appstream-test
#finish-args:
#  # X11 + XShm access
#  - --share=ipc
#  - --socket=x11
#  # Wayland access
#  - --socket=wayland
modules:
  - name: libappstream-glib
    buildsystem: meson
    config-opts:
      - -Dfonts=false
      - -Ddep11=false
      - -Drpm=false
      - -Dstemmer=false
    sources:
      #- type: archive
      #  url: https://people.freedesktop.org/~hughsient/appstream-glib/releases/appstream-glib-0.7.14.tar.xz
      #  sha256: 6dccad15f9d9a59dec6d259170a2010ee4a4b87475335a122a5d8b5e654a1a58
      - type: git
        url: https://github.com/hughsie/appstream-glib.git
        branch: master
        commit: 89d3d99c10e58f7a312ff15f2ade20d584f21d7e
    cleanup:
      - /share/installed-tests
  - name: appstream-test
    buildsystem: simple
    sources:
      - type: script
        commands:
          - appstream-util --version
          - appstream-util vercmp 'Build 9half' 'Build 10'
          - appstream-util vercmp 'Build 9.5' 'Build 10'
          - appstream-util vercmp 'Build 9+' 'Build 10'
          - appstream-util vercmp 'Build 9a' 'Build 10'
          - appstream-util vercmp 'Build 9' 'Build 10'
          - appstream-util vercmp '9half' '10'
          - appstream-util vercmp '9.5' '10'
          - appstream-util vercmp '9+' '10'
          - appstream-util vercmp '9a' '10'
          - appstream-util vercmp '9' '10'
        dest-filename: appstream-test
    build-commands:
      - install -p -D -m 0755 'appstream-test' -t '/app/bin/'
#cleanup:
#  - '*.la'
#  - '*.a'
```

Build command:
```
mkdir -p build && flatpak-builder 'build' 'org.freedesktop.appstream-test.yaml' --force-clean --install-deps-from='flathub'
```

Run command:
```
flatpak-builder --run 'build' 'org.freedesktop.appstream-test.yaml' 'appstream-test' 2>/dev/null
```

Results for appstream-util 0.7.13:
```
Version:	0.7.13
Build 9half > Build 10
Build 9.5 > Build 10
Build 9+ > Build 10
Build 9a > Build 10
Build 9 > Build 10
9half > 10
9.5 > 10
9+ > 10
9a > 10
9 < 10
```

Results for appstream-util 0.7.14:
```
Version:	0.7.14
Build 9half > Build 10
Build 9.5 > Build 10
Build 9+ > Build 10
Build 9a > Build 10
Build 9 > Build 10
9half > 10
9.5 > 10
9+ > 10
9a > 10
9 < 10
```

Results for appstream-util 0.7.14 (git commit: 89d3d99):
```
Version:	0.7.14
Build 9half > Build 10
Build 9.5 > Build 10
Build 9+ > Build 10
Build 9a > Build 10
Build 9 > Build 10
9half > 10
9.5 > 10
9+ > 10
9a > 10
9 < 10
```

As you can see, nothing has changed.

Validation of the [widelands.appdata.xml](https://raw.githubusercontent.com/widelands/widelands/600993f5051752cf7af2a9d572da0ffbb01d8089/debian/widelands.appdata.xml) on RHEL 7.5:
```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"
$ appstream-util --version
Version:	0.6.10
$ appstream-util validate-relax --nonet widelands.appdata.xml
widelands.appdata.xml: FAILED:
• tag-invalid           : <release> versions are not in order [Build 19 before Build 18]
• tag-invalid           : <release> versions are not in order [Build 18 before Build 17]
• tag-invalid           : <release> versions are not in order [Build 17 before Build 16]
• tag-invalid           : <release> versions are not in order [Build 16 before Build 15]
• tag-invalid           : <release> versions are not in order [Build 15 before Build 14]
• tag-invalid           : <release> versions are not in order [Build 14 before Build 13]
• tag-invalid           : <release> versions are not in order [Build 13 before Build 12]
• tag-invalid           : <release> versions are not in order [Build 12 before Build 11]
• tag-invalid           : <release> versions are not in order [Build 11 before Build 10]
• tag-invalid           : <release> versions are not in order [Build 10 before Build 9half]
• tag-invalid           : <release> versions are not in order [Build 9half before Build 9]
• tag-invalid           : <release> versions are not in order [Build 9 before Build 8]
• tag-invalid           : <release> versions are not in order [Build 8 before Build 7]
• tag-invalid           : <release> versions are not in order [Build 7 before Build 6]
• tag-invalid           : <release> versions are not in order [Build 6 before Build 5]
• tag-invalid           : <release> versions are not in order [Build 5 before Build 4]
• tag-invalid           : <release> versions are not in order [Build 4 before Build 3]
• tag-invalid           : <release> versions are not in order [Build 3 before Build 2]
• tag-invalid           : <release> versions are not in order [Build 2 before Build 1]
Validation of files failed
```

Validation of the [widelands.appdata.xml](https://raw.githubusercontent.com/widelands/widelands/600993f5051752cf7af2a9d572da0ffbb01d8089/debian/widelands.appdata.xml) on Freedesktop 18.08:
```
$ cat /etc/os-release
NAME=Freedesktop.org
VERSION="18.08 (Flatpak runtime)"
VERSION_ID=18.08
ID=org.freedesktop.Platform
$ appstream-util --version
Version:	0.7.13
$ appstream-util validate-relax --nonet widelands.appdata.xml
widelands.appdata.xml: FAILED:
• tag-invalid           : <release> versions are not in order [Build 10 before Build 9half]
Validation of files failed
```

**Comment by scx** [comment]
@hughsie 
@smcv 

The current version comparison mechanism is incompatible even with the dpkg implementation.

```
$ dpkg --compare-versions "10" gt "9.5" && echo "TRUE" || echo "FALSE"
TRUE
$ dpkg --compare-versions "9.5" gt "10" && echo "TRUE" || echo "FALSE"
FALSE
```

The results are the same for both 1.18.25 (EPEL7) and 1.9.0.5 (Ubuntu 18.04 LTS) versions.

Let me remind you how it works in appstream-util:

```
$ appstream-util vercmp "9.5" "10"
9.5 > 10
```

Could you just consider disabling comparison of the version order in validation?
https://github.com/hughsie/appstream-glib/blob/89d3d99c10e58f7a312ff15f2ade20d584f21d7e/libappstream-glib/as-app-validate.c#L938-L956

**Comment by scx** [comment]
@hughsie 

> > Could you just consider disabling checking of the version order in validation?
> 
> No -- various projects rely on the "first" release section being the "newest".

As you can see, we have several different standards of version comparison, and even more differences in the theirs implementations. AppStream has in fact created its own standard, instead of fully adopting an existing one, such as RPM (BTW, part of LSB AKA Linux Standard Base) or DEB.

> I could ask the same about Widelands; could it _just_ use a standard semver like `9.5` or `10.0` rather than the slightly odd `Build 9half`?

I agree that the "Build 9half" version is quite strange. I even wanted to propose a change to "9.5". However, it still does not solve the problem of comparing x with x.y (e.g. 10 vs 9.5). Both RPM and DEB world can handle it. Why can't AppStream do the same?

**Comment by hughsie** [comment]
> Both RPM and DEB world can handle it. Why can't AppStream do the same?

Can you please tone down the passive aggression please. We're all doing the best we can. If you do a pull request to make the version comparison parse and vercmp correctly (with passing tests) then I'll gladly review it, but I can't commit to spending a couple of days on this bug (which has a workaround, which is *use a an actual semver*...) right now.

**Comment by scx** [comment]
@hughsie 

> Can you please tone down the passive aggression please.

I don't see any "aggression" or hate in my speech. It was just a question (with a small suggestion). Anyway, I'm sorry if you took it that way.

> We're all doing the best we can.

I have no doubt about that and I really respect your work. However, I think that in this particular case, checking version order only brings unnecessary complications.

> If you do a pull request to make the version comparison parse and vercmp correctly (with passing tests) then I'll gladly review it, but I can't commit to spending a couple of days on this bug (which has a workaround, which is _use a an actual semver_...) right now.

I am afraid that at the moment I don't have the right qualifications to make such changes. This would require careful study of both RPM and DEB version comparison mechanisms. Unfortunately, not everything is included in the specification.
To be honest, I would rather use rpmdev-vercmp under the hood, but I'm afraid it would not be an acceptable solution.
Anyway, in my opinion it should be done at low level instead of separately in each package manager.

**Comment by scx** [comment]
@hughsie 
@smcv 

This may be a silly question, but why not just use the `rpmvercmp` from rpm?
https://github.com/rpm-software-management/rpm/blob/ca8ff08e4f61f05c743797ea4afbb9bf0bce3064/lib/rpmvercmp.c#L12-L122
Will it break something Debian-specific? I hope not.
AppStream-Glib already depends on rpm libs, so it shouldn't hurt anyone.
https://github.com/hughsie/appstream-glib/blob/89d3d99c10e58f7a312ff15f2ade20d584f21d7e/libappstream-builder/asb-package-rpm.c#L36

We can also make it more GLib-way, but I think that a simple call should be enough.
```
/* compare alpha and numeric segments of two versions */
/* return 1: a is newer than b */
/*        0: a and b are the same version */
/*       -1: b is newer than a */
gint
as_utils_vercmp_rpm (const gchar * a, const gchar * b)
{
    /* easy comparison to see if versions are identical */
    if (g_strcmp0(a, b) == 0) return 0;

    gchar oldch1, oldch2;
    gchar abuf[strlen(a)+1], bbuf[strlen(b)+1];
    gchar *str1 = abuf, *str2 = bbuf;
    gchar * one, * two;
    gint rc;
    gint isnum;

    g_strlcpy(str1, a, sizeof(str1));
    g_strlcpy(str2, b, sizeof(str2));

    one = str1;
    two = str2;

    /* loop through each version segment of str1 and str2 and compare them */
    while (*one || *two) {
	while (*one && !g_ascii_isalnum(*one) && *one != '~') one++;
	while (*two && !g_ascii_isalnum(*two) && *two != '~') two++;

	/* handle the tilde separator, it sorts before everything else */
	if (*one == '~' || *two == '~') {
	    if (*one != '~') return 1;
	    if (*two != '~') return -1;
	    one++;
	    two++;
	    continue;
	}

	/* If we ran to the end of either, we are finished with the loop */
	if (!(*one && *two)) break;

	str1 = one;
	str2 = two;

	/* grab first completely alpha or completely numeric segment */
	/* leave one and two pointing to the start of the alpha or numeric */
	/* segment and walk str1 and str2 to end of segment */
	if (g_ascii_isdigit(*str1)) {
	    while (*str1 && g_ascii_isdigit(*str1)) str1++;
	    while (*str2 && g_ascii_isdigit(*str2)) str2++;
	    isnum = 1;
	} else {
	    while (*str1 && g_ascii_isalpha(*str1)) str1++;
	    while (*str2 && g_ascii_isalpha(*str2)) str2++;
	    isnum = 0;
	}

	/* save character at the end of the alpha or numeric segment */
	/* so that they can be restored after the comparison */
	oldch1 = *str1;
	*str1 = '\0';
	oldch2 = *str2;
	*str2 = '\0';

	/* this cannot happen, as we previously tested to make sure that */
	/* the first string has a non-null segment */
	if (one == str1) return -1;	/* arbitrary */

	/* take care of the case where the two version segments are */
	/* different types: one numeric, the other alpha (i.e. empty) */
	/* numeric segments are always newer than alpha segments */
	/* XXX See patch #60884 (and details) from bugzilla #50977. */
	if (two == str2) return (isnum ? 1 : -1);

	if (isnum) {
	    gsize onelen, twolen;
	    /* this used to be done by converting the digit segments */
	    /* to ints using atoi() - it's changed because long  */
	    /* digit segments can overflow an int - this should fix that. */

	    /* throw away any leading zeros - it's a number, right? */
	    while (*one == '0') one++;
	    while (*two == '0') two++;

	    /* whichever number has more digits wins */
	    onelen = strlen(one);
	    twolen = strlen(two);
	    if (onelen > twolen) return 1;
	    if (twolen > onelen) return -1;
	}

	/* strcmp will return which one is greater - even if the two */
	/* segments are alpha or if they are numeric.  don't return  */
	/* if they are equal because there might be more segments to */
	/* compare */
	rc = g_strcmp0(one, two);
	if (rc) return (rc < 1 ? -1 : 1);

	/* restore character that was replaced by null above */
	*str1 = oldch1;
	one = str1;
	*str2 = oldch2;
	two = str2;
    }

    /* this catches the case where all numeric and alpha segments have */
    /* compared identically but the segment sepparating characters were */
    /* different */
    if ((!*one) && (!*two)) return 0;

    /* whichever version still has characters left over wins */
    if (!*one) return -1; else return 1;
}
```

**Comment by scx** [comment]
AppStream docs says: `The version compare algorithm is also used by RPM.`
https://www.freedesktop.org/software/appstream/docs/api/appstream-as-utils.html#as-utils-compare-versions
However, as we already know, it is simply not true. So, again, why just not use `rpmvercmp` from rpm or adapt it, if you don't want to depend on rpm libs? Are there any obstacles to this?

**Comment by scx** [comment]
Proposed patch: [libappstream-glib-rpmvercmp.patch](https://paste.ubuntu.com/p/TfVMpjJBNr/)
```
diff -Naur a/appstream-glib/libappstream-glib/as-utils.c b/appstream-glib/libappstream-glib/as-utils.c
--- a/appstream-glib/libappstream-glib/as-utils.c	2018-11-13 06:28:45.000000000 +0100
+++ b/appstream-glib/libappstream-glib/as-utils.c	2018-11-13 08:55:25.000000000 +0100
@@ -1463,6 +1463,209 @@
 }
 
 /**
+ * as_utils_version_reparse:
+ * @version: A version number
+ *
+ * Returns a dotted decimal version string from a version string. The supported
+ * formats are:
+ *
+ * - Dotted decimal, e.g. "1.2.3"
+ * - Base 16, a hex number *with* a 0x prefix, e.g. "0x10203"
+ *
+ * Anything with a '.' or that doesn't match 0x[a-f,0-9] is considered
+ * a string and returned without modification.
+ *
+ * Returns: A version number, e.g. "1.0.3"
+ *
+ * Since: 0.7.15
+ */
+gchar *
+as_utils_version_reparse (const gchar *version)
+{
+	const gchar *version_noprefix = version;
+	gchar *endptr = NULL;
+	guint64 tmp;
+	guint base;
+
+	/* already dotted decimal */
+	if (g_strstr_len (version, -1, ".") != NULL)
+		return g_strdup (version);
+
+	/* convert 0x prefixed strings to dotted decimal */
+	if (g_str_has_prefix (version, "0x")) {
+		version_noprefix += 2;
+		base = 16;
+	} else {
+		/* just return the string */
+		return g_strdup (version);
+	}
+
+	/* convert */
+	tmp = g_ascii_strtoull (version_noprefix, &endptr, base);
+	if (endptr != NULL && endptr[0] != '\0')
+		return g_strdup (version);
+	if (tmp == 0)
+		return g_strdup (version);
+	return as_utils_version_from_uint32 ((guint32) tmp, AS_VERSION_PARSE_FLAG_USE_TRIPLET);
+}
+
+// Based on: https://github.com/rpm-software-management/rpm/blob/ca8ff08e4f61f05c743797ea4afbb9bf0bce3064/lib/rpmvercmp.c#L12-L122
+/**
+ * as_utils_vercmp_rpm:
+ * @version_a: the release version, e.g. 1.2.3
+ * @version_b: the release version, e.g. 1.2.3.1
+ *
+ * Compares version numbers for sorting.
+ *
+ * Returns: -1 if a < b, +1 if a > b, 0 if they are equal
+ *
+ * Since: 0.7.15
+ */
+gint
+as_utils_vercmp_rpm (const gchar *version_a, const gchar *version_b)
+{
+	/* easy comparison to see if versions are identical */
+	if (g_strcmp0(version_a, version_b) == 0) return 0;
+
+	gchar oldch1, oldch2;
+	gchar abuf[strlen(version_a)+1], bbuf[strlen(version_b)+1];
+	gchar *str1 = abuf, *str2 = bbuf;
+	gchar * one, * two;
+	gint rc;
+	gint isnum;
+
+	g_strlcpy(str1, version_a, sizeof(abuf));
+	g_strlcpy(str2, version_b, sizeof(bbuf));
+
+	one = str1;
+	two = str2;
+
+	/* loop through each version segment of str1 and str2 and compare them */
+	while (*one || *two) {
+	while (*one && !g_ascii_isalnum(*one) && *one != '~') one++;
+	while (*two && !g_ascii_isalnum(*two) && *two != '~') two++;
+
+	/* handle the tilde separator, it sorts before everything else */
+	if (*one == '~' || *two == '~') {
+		if (*one != '~') return 1;
+		if (*two != '~') return -1;
+		one++;
+		two++;
+		continue;
+	}
+
+	/* If we ran to the end of either, we are finished with the loop */
+	if (!(*one && *two)) break;
+
+	str1 = one;
+	str2 = two;
+
+	/* grab first completely alpha or completely numeric segment */
+	/* leave one and two pointing to the start of the alpha or numeric */
+	/* segment and walk str1 and str2 to end of segment */
+	if (g_ascii_isdigit(*str1)) {
+		while (*str1 && g_ascii_isdigit(*str1)) str1++;
+		while (*str2 && g_ascii_isdigit(*str2)) str2++;
+		isnum = 1;
+	} else {
+		while (*str1 && g_ascii_isalpha(*str1)) str1++;
+		while (*str2 && g_ascii_isalpha(*str2)) str2++;
+		isnum = 0;
+	}
+
+	/* save character at the end of the alpha or numeric segment */
+	/* so that they can be restored after the comparison */
+	oldch1 = *str1;
+	*str1 = '\0';
+	oldch2 = *str2;
+	*str2 = '\0';
+
+	/* this cannot happen, as we previously tested to make sure that */
+	/* the first string has a non-null segment */
+	if (one == str1) return -1;	/* arbitrary */
+
+	/* take care of the case where the two version segments are */
+	/* different types: one numeric, the other alpha (i.e. empty) */
+	/* numeric segments are always newer than alpha segments */
+	/* XXX See patch #60884 (and details) from bugzilla #50977. */
+	if (two == str2) return (isnum ? 1 : -1);
+
+	if (isnum) {
+		gsize onelen, twolen;
+		/* this used to be done by converting the digit segments */
+		/* to ints using atoi() - it's changed because long  */
+		/* digit segments can overflow an int - this should fix that. */
+
+		/* throw away any leading zeros - it's a number, right? */
+		while (*one == '0') one++;
+		while (*two == '0') two++;
+
+		/* whichever number has more digits wins */
+		onelen = strlen(one);
+		twolen = strlen(two);
+		if (onelen > twolen) return 1;
+		if (twolen > onelen) return -1;
+	}
+
+	/* strcmp will return which one is greater - even if the two */
+	/* segments are alpha or if they are numeric.  don't return  */
+	/* if they are equal because there might be more segments to */
+	/* compare */
+	rc = g_strcmp0(one, two);
+	if (rc) return (rc < 1 ? -1 : 1);
+
+	/* restore character that was replaced by null above */
+	*str1 = oldch1;
+	one = str1;
+	*str2 = oldch2;
+	two = str2;
+	}
+
+	/* this catches the case where all numeric and alpha segments have */
+	/* compared identically but the segment sepparating characters were */
+	/* different */
+	if ((!*one) && (!*two)) return 0;
+
+	/* whichever version still has characters left over wins */
+	if (!*one) return -1; else return 1;
+}
+
+/**
+ * as_utils_vercmp_complex:
+ * @version_a: the release version, e.g. 1.2.3
+ * @version_b: the release version, e.g. 1.2.3.1
+ * @flags: some #AsVersionCompareFlag
+ *
+ * Compares version numbers for sorting.
+ *
+ * Returns: -1 if a < b, +1 if a > b, 0 if they are equal, and %G_MAXINT on error
+ *
+ * Since: 0.7.15
+ */
+gint
+as_utils_vercmp_complex (const gchar *version_a,
+			 const gchar *version_b,
+			 AsVersionCompareFlag flags)
+{
+	/* sanity check */
+	if (version_a == NULL || version_b == NULL)
+		return G_MAXINT;
+
+	/* optimisation */
+	if (g_strcmp0 (version_a, version_b) == 0)
+		return 0;
+
+	/* split into sections, and try to parse */
+	if (flags & AS_VERSION_COMPARE_FLAG_USE_HEURISTICS) {
+		g_autofree gchar *str_a = as_utils_version_reparse (version_a);
+		g_autofree gchar *str_b = as_utils_version_reparse (version_b);
+		return as_utils_vercmp_rpm (str_a, str_b);
+	} else {
+		return as_utils_vercmp_rpm (version_a, version_b);
+	}
+}
+
+/**
  * as_utils_vercmp:
  * @version_a: the release version, e.g. 1.2.3
  * @version_b: the release version, e.g. 1.2.3.1
@@ -1476,8 +1679,8 @@
 gint
 as_utils_vercmp (const gchar *version_a, const gchar *version_b)
 {
-	return as_utils_vercmp_full (version_a, version_b,
-				     AS_VERSION_COMPARE_FLAG_USE_HEURISTICS);
+	return as_utils_vercmp_complex (version_a, version_b,
+					AS_VERSION_COMPARE_FLAG_USE_HEURISTICS);
 }
 
 /**
diff -Naur a/appstream-glib/libappstream-glib/as-utils.h b/appstream-glib/libappstream-glib/as-utils.h
--- a/appstream-glib/libappstream-glib/as-utils.h	2018-11-13 06:28:45.000000000 +0100
+++ b/appstream-glib/libappstream-glib/as-utils.h	2018-11-13 08:39:21.000000000 +0100
@@ -163,6 +163,12 @@
 gint		 as_utils_vercmp_full		(const gchar	*version_a,
 						 const gchar	*version_b,
 						 AsVersionCompareFlag flags);
+gchar		*as_utils_version_reparse	(const gchar	*version);
+gint		 as_utils_vercmp_rpm		(const gchar	*version_a,
+						 const gchar	*version_b);
+gint		 as_utils_vercmp_complex	(const gchar	*version_a,
+						 const gchar	*version_b,
+						 AsVersionCompareFlag flags);
 gint		 as_utils_vercmp		(const gchar	*version_a,
 						 const gchar	*version_b);
 gboolean	 as_utils_guid_is_valid		(const gchar	*guid);
```

This patch deprecates the following functions:
- as_utils_vercmp_full
- as_utils_version_parse

If you want, I can just insert the code from as_utils_vercmp_complex and as_utils_version_reparse into them.

I also prepared a simple test: [org.freedesktop.appstream-test.yaml](https://paste.ubuntu.com/p/MS6kJBgzcR/)
```
app-id: org.freedesktop.appstream-test
runtime: org.freedesktop.Platform
runtime-version: '18.08'
sdk: org.freedesktop.Sdk
command: appstream-test
modules:
  - name: libappstream-glib
    buildsystem: meson
    config-opts:
      - -Dfonts=false
      - -Ddep11=false
      - -Drpm=false
      - -Dstemmer=false
    sources:
      #- type: archive
      #  url: https://people.freedesktop.org/~hughsient/appstream-glib/releases/appstream-glib-0.7.14.tar.xz
      #  sha256: 6dccad15f9d9a59dec6d259170a2010ee4a4b87475335a122a5d8b5e654a1a58
      - type: git
        url: https://github.com/hughsie/appstream-glib.git
        branch: master
        commit: 89d3d99c10e58f7a312ff15f2ade20d584f21d7e
      - type: patch
        path: libappstream-glib-rpmvercmp.patch
        strip-components: 2
    post-install:
      - meson test
    cleanup:
      - /share/installed-tests
  - name: appstream-test
    buildsystem: simple
    sources:
      - type: script
        commands:
          - appstream-util --version
          - appstream-util vercmp 'Build 9half' 'Build 10'
          - appstream-util vercmp 'Build 9.5' 'Build 10'
          - appstream-util vercmp 'Build 9+' 'Build 10'
          - appstream-util vercmp 'Build 9a' 'Build 10'
          - appstream-util vercmp 'Build 9' 'Build 10'
          - appstream-util vercmp '9half' '10'
          - appstream-util vercmp '9.5' '10'
          - appstream-util vercmp '9+' '10'
          - appstream-util vercmp '9a' '10'
          - appstream-util vercmp '9' '10'
        dest-filename: appstream-test
    build-commands:
      - install -p -D -m 0755 'appstream-test' -t '/app/bin/'
```

Build command:
```
mkdir -p build && flatpak-builder 'build' 'org.freedesktop.appstream-test.yaml' --force-clean --install-deps-from='flathub'
```

Run command:
```
flatpak-builder --run 'build' 'org.freedesktop.appstream-test.yaml' 'appstream-test' 2>/dev/null
```

Results:
```
Version:	0.7.14
Build 9half < Build 10
Build 9.5 < Build 10
Build 9+ < Build 10
Build 9a < Build 10
Build 9 < Build 10
9half < 10
9.5 < 10
9+ < 10
9a < 10
9 < 10
```
