### ISSUE TITLE
Please support icon width/height for DEP-11 cached icons

### ISSUE THREAD

**Issue by ximion** [hughsie/appstream-glib#98]
Hi!
The DEP-11 spec switched from cached icons being a single string:
```YAML
ID: org.example.Test
Icon:
  cached: test_test.png
  stock: test
```
to them being a list of dicts to make it possible to include a width/height:
```YAML
ID: org.example.Test
Icon:
  cached:
    - width: 64
      height: 64
      name: test_test.png
    - width: 128
      height: 128
      name: test_test.png
```
(from [libas tests](https://github.com/ximion/appstream/blob/master/tests/test-yamldata.c#L184))
See https://www.freedesktop.org/software/appstream/docs/sect-AppStream-DEP11.html#field-dep11-icon

This feature can be implemented in a backwards-compatible way, as has been done in AppStream/libappstream already. Unfortunately, keeping forward-compatibility wasn't possible with this, and the adoption rate of this change seems to be high (I've already seen this being used "in the wild").
So, having this supported in GNOME Software too would be important. It should also speed up the time you need to search for icons ;-)
Thanks!
    Matthias
